routes/admin.php
<?php

Route::group(['as' => 'uploads.', 'prefix' => 'uploads'], function () {
    Route::delete('{id}', 'Common\Uploads@destroy')->name('destroy');
});

Route::group(['prefix' => 'common'], function () {
    Route::get('companies/{company}/switch', 'Common\Companies@switch')->name('companies.switch');
    Route::get('companies/{company}/enable', 'Common\Companies@enable')->name('companies.enable');
    Route::get('companies/{company}/disable', 'Common\Companies@disable')->name('companies.disable');
    Route::resource('companies', 'Common\Companies');

    Route::get('dashboard/cashflow', 'Common\Dashboard@cashFlow')->name('dashboards.cashflow');
    Route::resource('dashboards', 'Common\Dashboard');

    Route::post('widgets/getData', 'Common\Widgets@getData')->name('widgets.getData');
    Route::resource('widgets', 'Common\Widgets');

    Route::get('import/{group}/{type}', 'Common\Import@create')->name('import.create');

    Route::get('items/autocomplete', 'Common\Items@autocomplete')->name('items.autocomplete');
    Route::post('items/total', 'Common\Items@total')->middleware(['money'])->name('items.total');
    Route::get('items/{item}/duplicate', 'Common\Items@duplicate')->name('items.duplicate');
    Route::post('items/import', 'Common\Items@import')->name('items.import');
    Route::get('items/export', 'Common\Items@export')->name('items.export');
    Route::get('items/{item}/enable', 'Common\Items@enable')->name('items.enable');
    Route::get('items/{item}/disable', 'Common\Items@disable')->name('items.disable');
    Route::resource('items', 'Common\Items', ['middleware' => ['money']]);

    Route::resource('search', 'Common\Search');

    Route::post('notifications/disable', 'Common\Notifications@disable')->name('notifications.disable');

    Route::post('bulk-actions/{group}/{type}', 'Common\BulkActions@action');

    Route::get('reports/{report}/print', 'Common\Reports@print')->name('reports.print');
    Route::get('reports/{report}/export', 'Common\Reports@export')->name('reports.export');
    Route::get('reports/groups', 'Common\Reports@groups')->name('reports.groups');
    Route::resource('reports', 'Common\Reports');
});

Route::group(['prefix' => 'auth'], function () {
    Route::get('logout', 'Auth\Login@destroy')->name('logout');

    Route::get('users/autocomplete', 'Auth\Users@autocomplete')->name('users.autocomplete');
    Route::get('users/{user}/read-bills', 'Auth\Users@readUpcomingBills')->name('users.read.bills');
    Route::get('users/{user}/read-invoices', 'Auth\Users@readOverdueInvoices')->name('users.read.invoices');
    Route::get('users/{user}/enable', 'Auth\Users@enable')->name('users.enable');
    Route::get('users/{user}/disable', 'Auth\Users@disable')->name('users.disable');
    Route::resource('users', 'Auth\Users');

    Route::resource('roles', 'Auth\Roles');

    Route::resource('permissions', 'Auth\Permissions');
});

Route::group(['prefix' => 'incomes'], function () {
    Route::get('invoices/{invoice}/sent', 'Incomes\Invoices@markSent')->name('invoices.sent');
    Route::get('invoices/{invoice}/email', 'Incomes\Invoices@emailInvoice')->name('invoices.email');
    Route::get('invoices/{invoice}/pay', 'Incomes\Invoices@markPaid')->name('invoices.paid');
    Route::get('invoices/{invoice}/print', 'Incomes\Invoices@printInvoice')->name('invoices.print');
    Route::get('invoices/{invoice}/pdf', 'Incomes\Invoices@pdfInvoice')->name('invoices.pdf');
    Route::get('invoices/{invoice}/duplicate', 'Incomes\Invoices@duplicate')->name('invoices.duplicate');
    Route::get('invoices/addItem', 'Incomes\Invoices@addItem')->middleware(['money'])->name('invoice.add.item');
    Route::post('invoices/import', 'Incomes\Invoices@import')->name('invoices.import');
    Route::get('invoices/export', 'Incomes\Invoices@export')->name('invoices.export');
    Route::resource('invoices', 'Incomes\Invoices', ['middleware' => ['date.format', 'money']]);

    Route::get('revenues/{revenue}/duplicate', 'Incomes\Revenues@duplicate')->name('revenues.duplicate');
    Route::post('revenues/import', 'Incomes\Revenues@import')->name('revenues.import');
    Route::get('revenues/export', 'Incomes\Revenues@export')->name('revenues.export');
    Route::resource('revenues', 'Incomes\Revenues', ['middleware' => ['date.format', 'money']]);

    Route::get('customers/currency', 'Incomes\Customers@currency');
    Route::get('customers/{customer}/duplicate', 'Incomes\Customers@duplicate')->name('customers.duplicate');
    Route::post('customers/field', 'Incomes\Customers@field')->name('customers.field');
    Route::post('customers/import', 'Incomes\Customers@import')->name('customers.import');
    Route::get('customers/export', 'Incomes\Customers@export')->name('customers.export');
    Route::get('customers/{customer}/enable', 'Incomes\Customers@enable')->name('customers.enable');
    Route::get('customers/{customer}/disable', 'Incomes\Customers@disable')->name('customers.disable');
    Route::get('customers/{customer}/currency', 'Incomes\Customers@currency')->name('customers.currency');
    Route::resource('customers', 'Incomes\Customers');
});

Route::group(['prefix' => 'expenses'], function () {
    Route::get('bills/{bill}/received', 'Expenses\Bills@markReceived')->name('bills.received');
    Route::get('bills/{bill}/print', 'Expenses\Bills@printBill')->name('bills.print');
    Route::get('bills/{bill}/pdf', 'Expenses\Bills@pdfBill')->name('bills.pdf');
    Route::get('bills/{bill}/duplicate', 'Expenses\Bills@duplicate')->name('bills.duplicate');
    Route::get('bills/addItem', 'Expenses\Bills@addItem')->middleware(['money'])->name('bill.add.item');
    Route::post('bills/import', 'Expenses\Bills@import')->name('bills.import');
    Route::get('bills/export', 'Expenses\Bills@export')->name('bills.export');
    Route::resource('bills', 'Expenses\Bills', ['middleware' => ['date.format', 'money']]);

    Route::get('payments/{payment}/duplicate', 'Expenses\Payments@duplicate')->name('payments.duplicate');
    Route::post('payments/import', 'Expenses\Payments@import')->name('payments.import');
    Route::get('payments/export', 'Expenses\Payments@export')->name('payments.export');
    Route::resource('payments', 'Expenses\Payments', ['middleware' => ['date.format', 'money']]);

    Route::get('vendors/currency', 'Expenses\Vendors@currency');
    Route::get('vendors/{vendor}/duplicate', 'Expenses\Vendors@duplicate')->name('vendors.duplicate');
    Route::post('vendors/import', 'Expenses\Vendors@import')->name('vendors.import');
    Route::get('vendors/export', 'Expenses\Vendors@export')->name('vendors.export');
    Route::get('vendors/{vendor}/enable', 'Expenses\Vendors@enable')->name('vendors.enable');
    Route::get('vendors/{vendor}/currency', 'Expenses\Vendors@currency')->name('vendors.currency');
    Route::get('vendors/{vendor}/disable', 'Expenses\Vendors@disable')->name('vendors.disable');
    Route::resource('vendors', 'Expenses\Vendors');
});

Route::group(['prefix' => 'banking'], function () {
    Route::get('accounts/currency', 'Banking\Accounts@currency')->name('accounts.currency');
    Route::get('accounts/{account}/enable', 'Banking\Accounts@enable')->name('accounts.enable');
    Route::get('accounts/{account}/disable', 'Banking\Accounts@disable')->name('accounts.disable');
    Route::resource('accounts', 'Banking\Accounts', ['middleware' => ['date.format', 'money']]);

    Route::post('transactions/import', 'Banking\Transactions@import')->name('transactions.import');
    Route::get('transactions/export', 'Banking\Transactions@export')->name('transactions.export');
    Route::resource('transactions', 'Banking\Transactions');

    Route::resource('transfers', 'Banking\Transfers', ['middleware' => ['date.format', 'money']]);

    Route::post('reconciliations/calculate', 'Banking\Reconciliations@calculate')->middleware(['money']);
    Route::patch('reconciliations/calculate', 'Banking\Reconciliations@calculate')->middleware(['money']);
    Route::resource('reconciliations', 'Banking\Reconciliations', ['middleware' => ['date.format', 'money']]);
});

Route::group(['prefix' => 'settings'], function () {
    Route::post('categories/category', 'Settings\Categories@category');
    Route::get('categories/{category}/enable', 'Settings\Categories@enable')->name('categories.enable');
    Route::get('categories/{category}/disable', 'Settings\Categories@disable')->name('categories.disable');
    Route::resource('categories', 'Settings\Categories');

    Route::get('currencies/currency', 'Settings\Currencies@currency');
    Route::get('currencies/config', 'Settings\Currencies@config');
    Route::get('currencies/{currency}/enable', 'Settings\Currencies@enable')->name('currencies.enable');
    Route::get('currencies/{currency}/disable', 'Settings\Currencies@disable')->name('currencies.disable');
    Route::resource('currencies', 'Settings\Currencies');

    Route::get('taxes/{tax}/enable', 'Settings\Taxes@enable')->name('taxes.enable');
    Route::get('taxes/{tax}/disable', 'Settings\Taxes@disable')->name('taxes.disable');
    Route::resource('taxes', 'Settings\Taxes');

    Route::group(['as' => 'settings.'], function () {
        Route::get('settings', 'Settings\Settings@index')->name('index');
        Route::patch('settings', 'Settings\Settings@update')->name('update');
        Route::get('company', 'Settings\Company@edit')->name('company.edit');
        Route::get('localisation', 'Settings\Localisation@edit')->name('localisation.edit');
        Route::get('invoice', 'Settings\Invoice@edit')->name('invoice.edit');
        Route::get('default', 'Settings\Defaults@edit')->name('default.edit');
        Route::get('email', 'Settings\Email@edit')->name('email.edit');
        Route::patch('email', 'Settings\Email@update')->name('email.update');
        Route::get('schedule', 'Settings\Schedule@edit')->name('schedule.edit');

        Route::get('{alias}', 'Settings\Modules@edit');

app/Models/Income/InvoiceHistory.php
<?php

namespace App\Models\Income;

use App\Abstracts\Model;
use App\Traits\Currencies;

class InvoiceHistory extends Model
{

    use Currencies;

    protected $table = 'invoice_histories';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['company_id', 'invoice_id', 'status_code', 'notify', 'description'];

    public function invoice()
    {
        return $this->belongsTo('App\Models\Income\Invoice');
    }

    public function status()
    {
        return $this->belongsTo('App\Models\Income\InvoiceStatus', 'status_code', 'code');
    }
}

app/Http/Controllers/Api/Incomes/InvoiceTransactions.php
<?php

namespace App\Http\Controllers\Api\Incomes;

use App\Http\Requests\Banking\Transaction as Request;
use App\Jobs\Banking\CreateDocumentTransaction;
use App\Jobs\Banking\DeleteTransaction;
use App\Models\Banking\Transaction;
use App\Models\Income\Invoice;
use App\Transformers\Banking\Transaction as Transformer;
use Dingo\Api\Routing\Helpers;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class InvoiceTransactions extends BaseController
{
    use Helpers, AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    /**
     * Display a listing of the resource.
     *
     * @param  $invoice_id
     * @return \Dingo\Api\Http\Response
     */
    public function index($invoice_id)
    {
        $transactions = Transaction::document($invoice_id)->get();

        return $this->response->collection($transactions, new Transformer());
    }

    /**
     * Display the specified resource.
     *
     * @param  $invoice_id
     * @param  $id
     * @return \Dingo\Api\Http\Response
     */
    public function show($invoice_id, $id)
    {
        $transaction = Transaction::document($invoice_id)->find($id);

        return $this->response->item($transaction, new Transformer());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  $invoice_id
     * @param  $request
     * @return \Dingo\Api\Http\Response
     */
    public function store($invoice_id, Request $request)
    {
        $invoice = Invoice::find($invoice_id);

        $transaction = $this->dispatch(new CreateDocumentTransaction($invoice, $request));

        return $this->response->created(url('api/invoices/' . $invoice_id . '/transactions/' . $transaction->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  $invoice_id
     * @param  $id
     * @return \Dingo\Api\Http\Response
     */
    public function destroy($invoice_id, $id)
    {
        $transaction = Transaction::document($invoice_id)->find($id);

        $this->dispatch(new DeleteTransaction($transaction));

        return $this->response->noContent();
    }
}

app/Http/Controllers/Api/Incomes/Invoices.php
<?php

namespace App\Http\Controllers\Api\Incomes;

use App\Abstracts\Http\ApiController;
use App\Http\Requests\Income\Invoice as Request;
use App\Jobs\Income\CreateInvoice;
use App\Jobs\Income\DeleteInvoice;
use App\Jobs\Income\UpdateInvoice;
use App\Models\Income\Invoice;
use App\Transformers\Income\Invoice as Transformer;

class Invoices extends ApiController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Dingo\Api\Http\Response
     */
    public function index()
    {
        $invoices = Invoice::with(['contact', 'status', 'items', 'transactions', 'histories'])->collect(['invoiced_at'=> 'desc']);

        return $this->response->paginator($invoices, new Transformer());
    }

    /**
     * Display the specified resource.
     *
     * @param  $id
     * @return \Dingo\Api\Http\Response
     */
    public function show($id)
    {
        // Check if we're querying by id or number
        if (is_numeric($id)) {
            $invoice = Invoice::find($id);
        } else {
            $invoice = Invoice::where('invoice_number', $id)->first();
        }

        return $this->response->item($invoice, new Transformer());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  $request
     * @return \Dingo\Api\Http\Response
     */
    public function store(Request $request)
    {
        $invoice = $this->dispatch(new CreateInvoice($request));

        return $this->response->created(url('api/invoices/' . $invoice->id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  $invoice
     * @param  $request
     * @return \Dingo\Api\Http\Response
     */
    public function update(Invoice $invoice, Request $request)
    {
        $invoice = $this->dispatch(new UpdateInvoice($invoice, $request));

        return $this->response->item($invoice->fresh(), new Transformer());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Invoice  $invoice
     * @return \Dingo\Api\Http\Response
     */
    public function destroy(Invoice $invoice)
    {
        try {
            $this->dispatch(new DeleteInvoice($invoice));

            return $this->response->noContent();
        } catch(\Exception $e) {
            $this->response->errorUnauthorized($e->getMessage());
        }
    }
}

app/Http/Controllers/Modals/Customers.php
<?php

namespace App\Http\Controllers\Modals;

use App\Abstracts\Http\Controller;
use App\Http\Requests\Common\Contact as Request;
use App\Models\Common\Contact;
use App\Models\Setting\Currency;

class Customers extends Controller
{
    /**
     * Instantiate a new controller instance.
     */
    public function __construct()
    {
        // Add CRUD permission check
        $this->middleware('permission:create-incomes-customers')->only(['create', 'store', 'duplicate', 'import']);
        $this->middleware('permission:read-incomes-customers')->only(['index', 'show', 'edit', 'export']);
        $this->middleware('permission:update-incomes-customers')->only(['update', 'enable', 'disable']);
        $this->middleware('permission:delete-incomes-customers')->only('destroy');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $currencies = Currency::enabled()->orderBy('name')->pluck('name', 'code')->toArray();

        $contact_selector = false;

        if (request()->has('contact_selector')) {
            $contact_selector = request()->get('contact_selector');
        }

        $rand = rand();

        $html = view('modals.customers.create', compact('currencies', 'contact_selector', 'rand'))->render();

        return response()->json([
            'success' => true,
            'error' => false,
            'message' => 'null',
            'html' => $html,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $request['enabled'] = 1;

        $customer = Contact::create($request->all());

        $message = trans('messages.success.added', ['type' => trans_choice('general.customers', 1)]);

        return response()->json([
            'success' => true,
            'error' => false,
            'data' => $customer,
            'message' => $message,
            'html' => 'null',
        ]);
    }
}

resources/views/incomes/customers/create.blade.php
@extends('layouts.admin')

@section('title', trans('general.title.new', ['type' => trans_choice('general.customers', 1)]))

@section('content')
    <div class="card">
        {!! Form::open([
            'route' => 'customers.store',
            'id' => 'customer',
            '@submit.prevent' => 'onSubmit',
            '@keydown' => 'form.errors.clear($event.target.name)',
            'files' => true,
            'role' => 'form',
            'autocomplete' => "off",
            'class' => 'form-loading-button needs-validation',
            'novalidate' => 'true'
        ]) !!}

        <div class="card-body">
            <div class="row">
                {{ Form::textGroup('name', trans('general.name'), 'user') }}

                {{ Form::textGroup('email', trans('general.email'), 'envelope', ['autocomplete' => 'off']) }}

                {{ Form::textGroup('tax_number', trans('general.tax_number'), 'percent', []) }}

                {{ Form::selectGroup('currency_code', trans_choice('general.currencies', 1), 'exchange-alt', $currencies, setting('default.currency')) }}

                {{ Form::textGroup('phone', trans('general.phone'), 'phone', []) }}

                {{ Form::textGroup('website', trans('general.website'), 'globe', []) }}

                {{ Form::textareaGroup('address', trans('general.address')) }}

                {{ Form::textGroup('reference', trans('general.reference'), 'file', []) }}

                {{ Form::radioGroup('enabled', trans('general.enabled'), true) }}

                @stack('create_user_input_start')
                    <div id="customer-create-user" class="form-group col-md-12 margin-top">
                        <div class="custom-control custom-checkbox">
                            {{ Form::checkbox('create_user', '1', null, [
                                'v-model' => 'form.create_user',
                                'id' => 'create_user',
                                'class' => 'custom-control-input',
                                '@input' => 'onCanLogin($event)'
                            ]) }}

                            <label class="custom-control-label" for="create_user">
                                <strong>{{ trans('customers.can_login') }}</strong>
                            </label>
                        </div>
                    </div>
                @stack('create_user_input_end')

                <div v-if="can_login" class="row col-md-12">
                    {{Form::passwordGroup('password', trans('auth.password.current'), 'key', [], 'col-md-6 password')}}

                    {{Form::passwordGroup('password_confirmation', trans('auth.password.current_confirm'), 'key', [], 'col-md-6 password')}}
                </div>
            </div>
        </div>

        <div class="card-footer">
            <div class="row float-right">
                {{ Form::saveButtons('incomes/customers') }}
            </div>
        </div>

        {{ Form::hidden('type', 'customer') }}

        {!! Form::close() !!}
    </div>
@endsection

@push('scripts_start')
    <script>
        var can_login_errors = {
            valid: '{{ trans('validation.required', ['attribute' => 'email']) }}',
            email: '{{ trans('customers.error.email') }}'
        };
    </script>

    <script src="{{ asset('public/js/incomes/customers.js?v=' . version('short')) }}"></script>
@endpush

resources/views/incomes/customers/index.blade.php
@extends('layouts.admin')

@section('title', trans_choice('general.customers', 2))

@section('new_button')
    @permission('create-incomes-customers')
        <span><a href="{{ url('incomes/customers/create') }}" class="btn btn-success btn-sm header-button-top"><span class="fa fa-plus"></span> &nbsp;{{ trans('general.add_new') }}</a></span>
        <span><a href="{{ url('common/import/incomes/customers') }}" class="btn btn-white btn-sm header-button-top"><span class="fa fa-upload"></span> &nbsp;{{ trans('import.import') }}</a></span>
    @endpermission
    <span><a href="{{ route('customers.export', request()->input()) }}" class="btn btn-white btn-sm header-button-top"><span class="fa fa-download"></span> &nbsp;{{ trans('general.export') }}</a></span>
@endsection

@section('content')
    @if ($customers->count())
        <div class="card">
            <div class="card-header border-bottom-0" v-bind:class="[bulk_action.show ? 'bg-gradient-primary' : '']">
                {!! Form::open([
                    'url' => 'incomes/customers',
                    'role' => 'form',
                    'method' => 'GET',
                    'class' => 'mb-0'
                ]) !!}
                    <div class="row" v-if="!bulk_action.show">
                        <div class="col-12 d-flex align-items-center">
                            <span class="font-weight-400 d-none d-lg-block mr-2">{{ trans('general.search') }}:</span>
                            <akaunting-search></akaunting-search>
                        </div>
                    </div>

                    {{ Form::bulkActionRowGroup('general.customers', $bulk_actions, 'incomes/customers') }}
                {!! Form::close() !!}
            </div>

            <div class="table-responsive">
                <table class="table table-flush table-hover">
                    <thead class="thead-light">
                        <tr class="row table-head-line">
                            <th class="col-sm-2 col-md-1 col-lg-1 col-xl-1 d-none d-sm-block">{{ Form::bulkActionAllGroup() }}</th>
                            <th class="col-xs-4 col-sm-3 col-md-3 col-lg-3 col-xl-3">@sortablelink('name', trans('general.name'), ['filter' => 'active, visible'], ['class' => 'col-aka', 'rel' => 'nofollow'])</th>
                            <th class="col-md-2 col-lg-2 col-xl-2 d-none d-md-block">@sortablelink('email', trans('general.email'))</th>
                            <th class="col-sm-3 col-md-2 col-lg-2 col-xl-2 d-none d-sm-block">@sortablelink('phone', trans('general.phone'))</th>
                            <th class="col-lg-2 col-xl-2 text-right d-none d-lg-block">@sortablelink('unpaid', trans('general.unpaid'))</th>
                            <th class="col-xs-4 col-sm-2 col-md-2 col-lg-1 col-xl-1">@sortablelink('enabled', trans('general.enabled'))</th>
                            <th class="col-xs-4 col-sm-2 col-md-2 col-lg-1 col-xl-1 text-center">{{ trans('general.actions') }}</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($customers as $item)
                            <tr class="row align-items-center border-top-1">
                                <td class="col-sm-2 col-md-1 col-lg-1 col-xl-1 d-none d-sm-block">
                                    {{ Form::bulkActionGroup($item->id, $item->name) }}
                                </td>
                                <td class="col-xs-4 col-sm-3 col-md-3 col-lg-3 col-xl-3">
                                    <a class="col-aka text-success" href="{{ route('customers.show', $item->id) }}">{{ $item->name }}</a>
                                </td>
                                <td class="col-md-2 col-lg-2 col-xl-2 d-none d-md-block long-texts">
                                    {{ !empty($item->email) ? $item->email : trans('general.na') }}
                                </td>
                                <td class="col-sm-3 col-md-2 col-lg-2 col-xl-2 d-none d-sm-block long-texts">
                                    {{ $item->phone }}
                                </td>
                                <td class="col-lg-2 col-xl-2 text-right d-none d-lg-block long-texts">
                                    @money($item->unpaid, setting('default.currency'), true)
                                </td>
                                <td class="col-xs-4 col-sm-2 col-md-2 col-lg-1 col-xl-1">
                                    @if (user()->can('update-incomes-customers'))
                                        {{ Form::enabledGroup($item->id, $item->name, $item->enabled) }}
                                    @else
                                        @if ($item->enabled)
                                            <badge rounded type="success">{{ trans('general.enabled') }}</badge>
                                        @else
                                            <badge rounded type="danger">{{ trans('general.disabled') }}</badge>
                                        @endif
                                    @endif
                                </td>
                                <td class="col-xs-4 col-sm-2 col-md-2 col-lg-1 col-xl-1 text-center">
                                    <div class="dropdown">
                                        <a class="btn btn-neutral btn-sm text-light items-align-center py-2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-ellipsis-h text-muted"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                            <a class="dropdown-item" href="{{ route('customers.show', $item->id) }}">{{ trans('general.show') }}</a>
                                                <a class="dropdown-item" href="{{ route('customers.edit', $item->id) }}">{{ trans('general.edit') }}</a>

                                                <div class="dropdown-divider"></div>
                                            @permission('create-incomes-customers')
                                                <a class="dropdown-item" href="{{ route('customers.duplicate', $item->id) }}">{{ trans('general.duplicate') }}</a>

                                                <div class="dropdown-divider"></div>
                                            @endpermission
                                            @permission('delete-incomes-customers')
                                                {!! Form::deleteLink($item, 'incomes/customers') !!}
                                            @endpermission
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="card-footer table-action">
                <div class="row">
                    @include('partials.admin.pagination', ['items' => $customers, 'type' => 'customers'])
                </div>
            </div>
        </div>
    @else
        @include('partials.admin.empty_page', ['page' => 'customers', 'docs_path' => 'incomes/customers'])
    @endif
@endsection

@push('scripts_start')
    <script src="{{ asset('public/js/incomes/customers.js?v=' . version('short')) }}"></script>
@endpush